# Generated by Django 5.2.2 on 2025-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_guitar_price_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='someone', max_length=100, verbose_name='Имя покупателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='someone', max_length=100, verbose_name='Фамилия покупателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество покупателя'),
        ),
    ]
